version: '3.1'
services:  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:8080  
  db:
    image: "postgres:latest"
    restart: always
    ports:
     - "5432:5432"
    env_file: .env